### ISSUE TITLE
Support SAN Certificates while DNS provider can be different per domain(s) groups

### ISSUE THREAD

**Issue by md2k** [xenolf/lego#242]
Hi @xenolf,  i faced with problem when i have several domains located across 2 DNS providers Route53/CloudFlare , but i have requirements to create SAN certificate which include mix of those domains.
So formally need some solution which provide possibility to solve challenge using different DNS providers  per domain(s).
Live case example:
* domainA.com  located on CloudFlare Account 1
* domainB.com located on Route53 Account 1
* domainC.com  located on CloudFlare Account 2
* domainD.com located on Route53 Account 2

Not always possible to have all domains placed in same location and under the same account.
Currently i use another library which support hooks, so i wrote custom hook implementation (using your providers implementation partly) which have own yaml configuration:
```yaml
providers:
  cloudflare:
    accounts:
      accountA:
        authdata:
          email: test@test.com
          api_key: XXXXXXXXXX
        domains:
          - A.test.com
          - A.example.com
  route53:
    accounts:
      AccountA:
        authdata:
          key_id: XXXXXXXXX
          access_key: XXXXXXXXXXX
        domains:
          - A.dummy.com
```

So now when i try to get certificate for 3 domains as SAN, hook will check configuration and will use required account and DNS provider.

My Idea to have maybe something similar for `lego`,  instead of tell to lego by CLI options what to do, to create some configuration module which can hold information about desired Certificate,  its domains and providers/accounts which should be sued for challenge solving.

I checked almost all available tools for LetsEncrypt, and no one something similar, but i think my use-case not only one, and such functionality as above may provide very nice flexibility and useful for automation.

I do not dive to deep yet into your application, so it is more question/discussion about possibilities.
