### ISSUE TITLE
httpreq endpoint format

### ISSUE THREAD

**Issue by Garogat** [xenolf/lego#796]
How is the correct HTTPREQ_ENDPOINT format for httpreq?
I have set it to `https://example.com/api/acme/` and this throws the following error:

`level=error msg="Unable to obtain ACME certificate for domains "sub.domain.tld" detected thanks to rule "Host:sub.domain.tld" : cannot get ACME client httpreq: parse "https://example.com/api/acme/": first path segment in URL cannot contain colon"`

Would be nice if you could add a working example to the README and maybe fix that error.

**Comment by ldez** [comment]
https://github.com/xenolf/lego/tree/master/providers/dns/httpreq

**Comment by Garogat** [comment]
Solved it.

I used quotation marks when setting the `HTTPREQ_ENDPOINT` variable in docker-compose. Without it is working.

Similar issue: https://github.com/influxdata/telegraf/issues/3794

Working `docker-compose.yml`:

```
version: '3'

services:
  traefik:
    image: traefik
    container_name: traefik
    environment:
      - HTTPREQ_ENDPOINT=https://example.com/api/acme/
      - HTTPREQ_USERNAME=masterofdns
      - HTTPREQ_PASSWORD=topsecret
    labels:
      - traefik.enable=true
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:traefik.example.com
      - traefik.port=8080
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
      - ./rules:/rules
```
